import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FaqFilters } from "@/components/faq/FaqFilters";
import { FaqList } from "@/components/faq/FaqList";
import { getFaqs, getGlobal } from "@/lib/strapi/queries";
import { isLocale } from "@/lib/i18n/config";
import { localizedHref } from "@/lib/i18n/routing";
import { createMetadata } from "@/lib/seo/metadata";
import type { Locale } from "@/types/content";

const categoryLabels: Record<string, { zh: string; en: string }> = { product: { zh: "产品", en: "Product" }, solution: { zh: "解决方案", en: "Solution" }, usage: { zh: "使用方法", en: "Usage" }, service: { zh: "服务", en: "Service" }, other: { zh: "其他", en: "Other" } };
type Search = { q?: string; category?: string; product?: string; solution?: string };
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const global = await getGlobal(locale); return createMetadata(null, { title: locale === "zh" ? "常见问题" : "FAQ", description: global?.siteDescription ?? undefined }); }
export default async function FaqPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<Search> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound(); const currentLocale = locale as Locale; const { q, category, product, solution } = await searchParams; const all = await getFaqs(currentLocale); const query = [q?.trim() ? `filters[question][$containsi]=${encodeURIComponent(q.trim())}` : "", category ? `filters[category][$eq]=${encodeURIComponent(category)}` : "", product ? `filters[products][slug][$eq]=${encodeURIComponent(product)}` : "", solution ? `filters[solutions][slug][$eq]=${encodeURIComponent(solution)}` : ""].filter(Boolean).join("&"); const faqs = query ? await getFaqs(currentLocale, query) : all; const categories = Object.keys(categoryLabels).map((value) => ({ value, label: categoryLabels[value][locale === "zh" ? "zh" : "en"] })); const products = Array.from(new Map(all.flatMap((f) => f.products ?? []).filter((x) => x.slug).map((x) => [x.slug, { value: x.slug, label: x.name ?? x.title ?? x.slug }])).values()); const solutions = Array.from(new Map(all.flatMap((f) => f.solutions ?? []).filter((x) => x.slug).map((x) => [x.slug, { value: x.slug, label: x.title ?? x.name ?? x.slug }])).values());
  return <section className="mx-auto max-w-5xl px-4 py-14 sm:px-6 lg:px-8"><header className="relative overflow-hidden rounded-3xl bg-brand-ink px-6 py-14 text-white sm:px-10"><p className="text-sm font-bold uppercase tracking-[0.2em] text-brand-lime">{locale === "zh" ? "知识中心" : "Knowledge center"}</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">{locale === "zh" ? "常见问题，快速找到答案" : "Clear answers to common questions"}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-200">{locale === "zh" ? "按产品、方案和使用场景查找包装设备与材料的实用信息。" : "Find practical answers about packaging equipment and materials by product, solution, or use case."}</p></header><div className="mt-10"><FaqFilters locale={currentLocale} q={q} category={category} product={product} solution={solution} categories={categories} products={products} solutions={solutions} /><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-brand-teal">{category ? categories.find((x) => x.value === category)?.label : (locale === "zh" ? "全部问题" : "All questions")}</p><h2 className="mt-2 text-2xl font-semibold text-brand-ink sm:text-3xl">{q ? (locale === "zh" ? `搜索“${q}”` : `Results for “${q}”`) : (locale === "zh" ? "常见问题" : "Frequently asked questions")}</h2></div><span className="text-sm text-brand-muted">{faqs.length} {locale === "zh" ? "个问题" : "questions"}</span></div>{faqs.length ? <FaqList items={faqs} locale={currentLocale} /> : <div className="brand-panel p-12 text-center"><p className="text-brand-muted">{locale === "zh" ? "没有找到匹配的问题。" : "No questions matched your filters."}</p><Link href={localizedHref(currentLocale, "/faq")} className="brand-button-primary mt-5">{locale === "zh" ? "查看全部问题" : "View all questions"}</Link></div>}</div></section>;
}
