"use client";
import Link from "next/link";
import { X } from "lucide-react";
import { useEffect, useRef } from "react";
import { localizedHref } from "@/lib/i18n/routing";
import type { Locale } from "@/lib/i18n/config";
import { messages, localizedCategoryName } from "@/lib/i18n/messages";
import type { NavigationItem, ProductCategory } from "@/types/content";
export function MobileNav({ locale, open, onClose, items, categories = [] }: { locale: Locale; open: boolean; onClose: () => void; items: NavigationItem[]; categories?: ProductCategory[] }) { const first = useRef<HTMLAnchorElement>(null); useEffect(() => { if (open) first.current?.focus(); }, [open]); useEffect(() => { if (!open) return; const handler = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [open, onClose]); if (!open) return null; return <div className="fixed inset-0 z-[100] min-h-screen bg-brand-ink/50 lg:hidden" role="presentation" onClick={onClose}><nav className="ml-auto flex min-h-screen w-[min(22rem,90vw)] flex-col gap-2 overflow-y-auto bg-white p-6 shadow-2xl" aria-label={messages[locale].menu} onClick={(e) => e.stopPropagation()}><button type="button" className="self-end rounded-lg p-2 text-brand-blue hover:bg-brand-teal/10" onClick={onClose} aria-label={messages[locale].close}><X size={20} /></button>{items.map((item, i) => <div key={`${item.href}-${i}`}><Link ref={i === 0 ? first : undefined} className="block rounded-lg px-3 py-3 text-lg font-semibold text-brand-ink hover:bg-brand-teal/10" href={item.external ? item.href : localizedHref(locale, item.href)} onClick={onClose}>{item.label}</Link>{item.href === "/products" && categories.length ? <div className="ml-3 border-l-2 border-brand-lime pl-3">{categories.map((category) => <Link key={category.id} className="block rounded px-3 py-2 text-sm text-brand-muted hover:text-brand-blue" href={localizedHref(locale, `/products?category=${category.slug}`)} onClick={onClose}>{localizedCategoryName(category.name, locale)}</Link>)}</div> : null}</div>)}</nav></div>; }

