import Link from "next/link";
import { Globe, Mail, MapPin, Phone, PlayCircle, Send } from "lucide-react";
import type { Global, ProductCategory } from "@/types/content";
import type { Locale } from "@/lib/i18n/config";
import { localizedHref } from "@/lib/i18n/routing";

const productLinks = ["Air Cushion Machine", "Air Cushion Film", "Paper Cushion", "Foam in Place", "Padded Mailer", "Gummed Paper Tape", "Air Column Bag", "Dunnage Bags"];
const aboutLinks = ["Overview", "Responsibility", "Factory Display", "FAQ", "Video", "Recommends", "Projects"];
export function SiteFooter({ locale, global, categories = [] }: { locale: Locale; global: Global | null; categories?: ProductCategory[] }) { const socials = [{ label: "LinkedIn", href: "https://www.linkedin.com/company/ameson-pak", icon: Send }, { label: "Facebook", href: "https://www.facebook.com/amesonpak", icon: Globe }, { label: "YouTube", href: "https://www.youtube.com/@amesonpak", icon: PlayCircle }]; return <footer className="mt-20 bg-brand-ink text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 md:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><p className="text-xl font-bold text-brand-lime">Ameson Packaging</p><p className="mt-4 text-sm leading-6 text-slate-300">{global?.footerText ?? "Professional packaging solutions for a more efficient world."}</p><div className="mt-6 flex gap-3">{socials.map(({ label, href, icon: Icon }) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={label} className="rounded-full bg-white/10 p-2.5 text-white hover:bg-brand-teal"><Icon size={17} /></a>)}</div></div><div><h2 className="font-semibold text-white">Products</h2><div className="mt-4 grid gap-2">{(categories.length ? categories.map((c) => c.name) : productLinks).map((name) => <Link key={name} href={localizedHref(locale, `/products?category=${encodeURIComponent(name.toLowerCase().replaceAll(" ", "-"))}`)} className="text-sm text-slate-300 hover:text-brand-lime">{name}</Link>)}</div></div><div><h2 className="font-semibold text-white">About</h2><div className="mt-4 grid gap-2">{aboutLinks.map((name) => <Link key={name} href={localizedHref(locale, "/about")} className="text-sm text-slate-300 hover:text-brand-lime">{name}</Link>)}<Link href={localizedHref(locale, "/blog")} className="text-sm text-slate-300 hover:text-brand-lime">Blog</Link><Link href={localizedHref(locale, "/contact")} className="text-sm text-slate-300 hover:text-brand-lime">Contact</Link></div></div><div><h2 className="font-semibold text-white">Contact</h2><div className="mt-4 grid gap-3 text-sm text-slate-300"><a className="flex gap-2 hover:text-brand-lime" href="mailto:sales@amesonpak.com"><Mail size={17} />sales@amesonpak.com</a><a className="flex gap-2 hover:text-brand-lime" href="tel:+865925538744"><Phone size={17} />+86 592 5538744 (CN)</a><a className="flex gap-2 hover:text-brand-lime" href="tel:+12146942210"><Phone size={17} />+1 214 694 2210 (US)</a><p className="flex gap-2"><MapPin size={17} className="shrink-0" />Xiamen Ameson New Material Inc.<br />No. 66 Kengping Road, Xiamen, China</p><p className="flex gap-2"><MapPin size={17} className="shrink-0" />Ameson (USA) Packaging Inc.<br />10482 Brockwood Rd, Dallas, TX</p></div></div></div><div className="border-t border-white/10 px-4 py-5 text-center text-xs text-slate-400">Copyright © 2006 - 2026 Ameson Packaging. All rights reserved.</div></footer>; }
