import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { VideoCard, videoCategoryLabel } from "@/components/videos/VideoCard";
import { VideoFilters } from "@/components/videos/VideoFilters";
import { getGlobal, getVideos } from "@/lib/strapi/queries";
import { createMetadata } from "@/lib/seo/metadata";
import { isLocale, type Locale } from "@/lib/i18n/config";
import { localizedHref } from "@/lib/i18n/routing";

type Search = { q?: string; category?: string; product?: string };
const productOptions = (items: Array<{ slug: string; name?: string; title?: string }>) => Array.from(new Map(items.filter((x) => x.slug).map((x) => [x.slug, { value: x.slug, label: x.name ?? x.title ?? x.slug }])).values());
const categoryValues = ["promotional", "introduction", "operation", "installation", "tutorial", "commissioning", "maintenance", "application", "factory", "company"];
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const global = await getGlobal(locale); return createMetadata(null, { title: locale === "zh" ? "视频中心" : "Video center", description: global?.siteDescription ?? undefined }); }
export default async function VideosPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<Search> }) { const { locale } = await params; if (!isLocale(locale)) notFound(); const currentLocale = locale as Locale; const { q, category, product } = await searchParams; const query = [q?.trim() ? `filters[title][$containsi]=${encodeURIComponent(q.trim())}` : "", category ? `filters[category][$eq]=${encodeURIComponent(category)}` : "", product ? `filters[products][slug][$eq]=${encodeURIComponent(product)}` : ""].filter(Boolean).join("&"); const [videos, allVideos] = await Promise.all([getVideos(currentLocale, query), getVideos(currentLocale)]); const products = productOptions(allVideos.flatMap((v) => v.products ?? [])); const categories = categoryValues.map((value) => ({ value, label: videoCategoryLabel(value, currentLocale) })); return <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><header className="relative overflow-hidden rounded-3xl bg-brand-ink px-6 py-14 text-white sm:px-10"><p className="text-sm font-bold uppercase tracking-[0.2em] text-brand-lime">{locale === "zh" ? "视频中心" : "Video center"}</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">{locale === "zh" ? "从安装到应用，了解包装设备的每一步" : "See packaging equipment in action"}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-200">{locale === "zh" ? "浏览产品介绍、操作教程、工厂展示和行业应用视频。" : "Browse product introductions, tutorials, factory tours, and industry applications."}</p></header><div className="mt-10"><VideoFilters locale={currentLocale} q={q} category={category} product={product} categories={categories} products={products} /><div className="mb-6 flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-brand-teal">{category ? videoCategoryLabel(category, currentLocale) : (locale === "zh" ? "全部视频" : "All videos")}</p><h2 className="mt-2 text-2xl font-semibold text-brand-ink sm:text-3xl">{q ? (locale === "zh" ? `搜索结果：“${q}”` : `Results for “${q}”`) : (locale === "zh" ? "精选视频" : "Featured videos")}</h2></div><span className="text-sm text-brand-muted">{videos.length} {locale === "zh" ? "个视频" : "videos"}</span></div>{videos.length ? <div className="grid gap-7 md:grid-cols-2 xl:grid-cols-3">{videos.map((video) => <VideoCard key={video.id} video={video} locale={currentLocale} />)}</div> : <div className="brand-panel p-12 text-center"><p className="text-brand-muted">{locale === "zh" ? "没有找到匹配的视频。" : "No videos matched your filters."}</p><Link href={localizedHref(currentLocale, "/videos")} className="brand-button-primary mt-5">{locale === "zh" ? "查看全部视频" : "View all videos"}</Link></div>}</div></section>; }
