import Image from "next/image";
import Link from "next/link";
import { Play, ArrowUpRight } from "lucide-react";
import type { Locale } from "@/lib/i18n/config";
import type { Video } from "@/types/content";
import { localizedHref } from "@/lib/i18n/routing";
import { resolveMediaUrl } from "@/lib/strapi/image";
const labels = { zh: { promotional: "产品宣传", introduction: "产品介绍", operation: "产品操作", installation: "安装教程", tutorial: "使用教程", commissioning: "设备调试", maintenance: "维护保养", application: "行业应用", factory: "工厂展示", company: "企业宣传" }, en: { promotional: "Promotional", introduction: "Product introduction", operation: "Operation", installation: "Installation", tutorial: "Tutorial", commissioning: "Commissioning", maintenance: "Maintenance", application: "Industry application", factory: "Factory tour", company: "Company" } } as const;
export const videoCategoryLabel = (category: string, locale: Locale) => (labels[locale === "zh" ? "zh" : "en"] as Record<string, string>)[category] ?? category;
export function VideoCard({ video, locale }: { video: Video; locale: Locale }) { const image = resolveMediaUrl(video.cover); return <article className="group brand-card overflow-hidden"><Link href={localizedHref(locale, `/videos/${video.slug}`)} className="block h-full"><div className="relative aspect-video overflow-hidden bg-brand-ink">{image ? <Image src={image} alt={video.cover?.alternativeText ?? video.title} fill sizes="(min-width: 1280px) 33vw, (min-width: 768px) 50vw, 100vw" className="object-cover transition duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-white"><Play size={32} /></div>}<span className="absolute bottom-3 left-3 rounded-full bg-brand-ink/85 px-3 py-1 text-xs font-semibold text-white">{videoCategoryLabel(video.category, locale)}</span></div><div className="flex min-h-48 flex-col p-6"><h2 className="text-xl font-semibold text-brand-ink">{video.title}</h2>{video.description ? <p className="mt-3 line-clamp-3 text-sm leading-6 text-brand-muted">{video.description}</p> : null}<span className="mt-auto flex items-center gap-2 pt-6 text-sm font-semibold text-brand-blue">{locale === "zh" ? "观看视频" : "Watch video"}<ArrowUpRight size={16} /></span></div></Link></article>; }
