import type { Metadata } from "next";
import { Mail, MapPin, Phone, Clock3 } from "lucide-react";
import { notFound } from "next/navigation";
import { getContactPage, getGlobal } from "@/lib/strapi/queries";
import { isLocale } from "@/lib/i18n/config";
import { createMetadata } from "@/lib/seo/metadata";
import { ContactForm } from "@/components/contact/ContactForm";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const [contact, global] = await Promise.all([getContactPage(locale), getGlobal(locale)]); return createMetadata(contact?.seo, { title: contact?.title ?? "Contact us", description: global?.siteDescription ?? undefined }); }
export default async function ContactPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; if (!isLocale(locale)) notFound(); const contact = await getContactPage(locale); if (!contact) return <section className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="text-3xl font-semibold text-brand-ink">Contact us</h1><p className="mt-4 text-brand-muted">Content unavailable</p></section>; const zh = locale === "zh"; return <article className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><header className="relative overflow-hidden rounded-3xl bg-brand-ink px-6 py-12 text-white sm:px-10"><div className="absolute -right-16 -top-24 h-64 w-64 rounded-full bg-brand-teal/30 blur-3xl" /><p className="relative text-sm font-bold uppercase tracking-[0.2em] text-brand-lime">{zh ? "联系我们" : "Contact us"}</p><h1 className="relative mt-4 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">{contact.title}</h1>{contact.intro ? <p className="relative mt-5 max-w-2xl text-lg leading-8 text-slate-200">{contact.intro}</p> : null}</header><div className="mt-10 grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><section className="brand-panel p-7 sm:p-9"><h2 className="text-xl font-semibold text-brand-ink">{zh ? "联系方式" : "Contact details"}</h2><dl className="mt-7 space-y-6 text-brand-ink">{contact.address ? <div className="flex gap-4"><MapPin className="mt-1 shrink-0 text-brand-teal" size={20} /><div><dt className="text-sm font-semibold text-brand-muted">{zh ? "地址" : "Address"}</dt><dd className="mt-1 leading-6">{contact.address}</dd></div></div> : null}{contact.phone ? <div className="flex gap-4"><Phone className="mt-1 shrink-0 text-brand-teal" size={20} /><div><dt className="text-sm font-semibold text-brand-muted">{zh ? "电话" : "Phone"}</dt><dd className="mt-1"><a href={`tel:${contact.phone}`} className="hover:text-brand-blue">{contact.phone}</a></dd></div></div> : null}{contact.email ? <div className="flex gap-4"><Mail className="mt-1 shrink-0 text-brand-teal" size={20} /><div><dt className="text-sm font-semibold text-brand-muted">Email</dt><dd className="mt-1"><a href={`mailto:${contact.email}`} className="hover:text-brand-blue">{contact.email}</a></dd></div></div> : null}{contact.officeHours ? <div className="flex gap-4"><Clock3 className="mt-1 shrink-0 text-brand-teal" size={20} /><div><dt className="text-sm font-semibold text-brand-muted">{zh ? "办公时间" : "Office hours"}</dt><dd className="mt-1 whitespace-pre-line leading-6">{contact.officeHours}</dd></div></div> : null}</dl></section><section className="brand-panel p-7 sm:p-9"><h2 className="text-2xl font-semibold text-brand-ink">{contact.formTitle ?? (zh ? "开始沟通" : "Start a conversation")}</h2>{contact.formIntro ? <p className="mt-3 text-brand-muted">{contact.formIntro}</p> : null}<ContactForm locale={locale} /></section></div></article>; }
