import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { MediaGallery } from "@/components/content/MediaGallery";
import { ProductTabs } from "@/components/products/ProductTabs";
import { RelatedProductsCarousel } from "@/components/products/RelatedProductsCarousel";
import { getProductBySlug, getRelatedProducts, getArticles } from "@/lib/strapi/queries";
import { isLocale } from "@/lib/i18n/config";
import { createMetadata } from "@/lib/seo/metadata";
import { resolveMediaUrl } from "@/lib/strapi/image";
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const {locale,slug}=await params;if(!isLocale(locale))return{};const p=await getProductBySlug(slug,locale);return createMetadata(p?.seo,{title:p?.name??"Product",description:p?.summary??undefined});}
export default async function ProductDetailPage({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;if(!isLocale(locale))notFound();const product=await getProductBySlug(slug,locale);if(!product)notFound();const [related,articles]=await Promise.all([getRelatedProducts(product.category?.slug,locale,product.slug),getArticles(locale)]);const cover=resolveMediaUrl(product.cover);return <article className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div>{cover&&<div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-slate-100"><Image src={cover} alt={product.cover?.alternativeText??product.name} fill priority className="object-cover"/></div>}<MediaGallery media={product.gallery} label={locale==="zh"?"产品图片":"Product gallery"}/></div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-700">{product.category?.name??(locale==="zh"?"产品":"Product")}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-slate-950">{product.name}</h1>{product.summary&&<p className="mt-6 text-lg leading-8 text-slate-600">{product.summary}</p>}{product.specifications?.length&&<dl className="mt-10 divide-y divide-slate-200 border-y">{product.specifications.map(s=><div key={s.label} className="grid grid-cols-2 gap-4 py-4 text-sm"><dt>{s.label}</dt><dd className="text-right">{s.value}</dd></div>)}</dl>}</div></div><ProductTabs product={product} locale={locale} blogs={articles.slice(0,6).map(a=>({title:a.title,slug:a.slug}))}/><RelatedProductsCarousel products={related} locale={locale}/></article>}
