import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, CalendarDays } from "lucide-react";
import { notFound } from "next/navigation";
import { getArticles, getGlobal } from "@/lib/strapi/queries";
import { isLocale } from "@/lib/i18n/config";
import { localizedHref } from "@/lib/i18n/routing";
import { resolveMediaUrl } from "@/lib/strapi/image";
import { createMetadata } from "@/lib/seo/metadata";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const global = await getGlobal(locale); return createMetadata(null, { title: locale === "zh" ? "博客" : "Blog", description: global?.siteDescription ?? undefined }); }
export default async function BlogPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; if (!isLocale(locale)) notFound(); const articles = await getArticles(locale); return <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><header className="relative overflow-hidden rounded-3xl bg-brand-ink px-6 py-14 text-white sm:px-10"><div className="absolute -right-20 -top-28 h-72 w-72 rounded-full bg-brand-teal/30 blur-3xl" /><p className="relative text-sm font-bold uppercase tracking-[0.2em] text-brand-lime">{locale === "zh" ? "知识与洞察" : "Knowledge & insight"}</p><h1 className="relative mt-4 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">{locale === "zh" ? "来自现场的洞察" : "Insights from the field"}</h1><p className="relative mt-5 max-w-2xl text-lg leading-8 text-slate-200">{locale === "zh" ? "了解包装创新、运营效率以及帮助团队持续前进的实践。" : "Explore packaging innovation, operational efficiency, and the practices that keep teams moving."}</p></header>{articles.length ? <div className="mt-10 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{articles.map((article) => { const image = resolveMediaUrl(article.cover); const date = article.publishedAt ? new Intl.DateTimeFormat(locale === "zh" ? "zh-CN" : "en-US", { dateStyle: "medium" }).format(new Date(article.publishedAt)) : null; return <article key={article.id} className="group brand-card overflow-hidden"><Link href={localizedHref(locale, `/blog/${article.slug}`)} className="block focus-visible:outline-2 focus-visible:outline-brand-teal">{image ? <div className="relative aspect-[16/9] overflow-hidden bg-slate-100"><Image src={image} alt={article.cover?.alternativeText ?? article.title} fill sizes="(min-width: 1024px) 33vw, 100vw" className="object-cover transition duration-500 group-hover:scale-105" /></div> : null}<div className="flex min-h-52 flex-col p-6"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-brand-teal"><CalendarDays size={14} />{date ?? (locale === "zh" ? "最新文章" : "Latest article")}</div><h2 className="mt-3 text-xl font-semibold text-brand-ink">{article.title}</h2>{article.description ? <p className="mt-3 line-clamp-3 text-sm leading-6 text-brand-muted">{article.description}</p> : null}<span className="mt-auto flex items-center gap-2 pt-6 text-sm font-semibold text-brand-blue">{locale === "zh" ? "阅读文章" : "Read article"}<ArrowUpRight size={16} /></span></div></Link></article>; })}</div> : <div className="brand-panel mt-10 p-12 text-center text-brand-muted">{locale === "zh" ? "暂无文章" : "No articles yet"}</div>}</section>; }
