import type { ElementType, ReactNode } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { Media } from "@/types/content";
import { resolveMediaUrl, resolveStrapiAssetUrl } from "@/lib/strapi/image";
import { ImageLightbox } from "@/components/content/ImageLightbox";
type Block = { type?: string; __component?: string; body?: string | null; title?: string | null; file?: Media | null; files?: Media[] | null; image?: Media | Media[] | null; children?: Array<{ text?: string; bold?: boolean; italic?: boolean; url?: string }>; level?: number; url?: string;[key: string]: unknown };
function inline(children: Block["children"]): ReactNode { return (children ?? []).map((c, i) => <span key={i} className={`${c.bold ? "font-semibold" : ""} ${c.italic ? "italic" : ""}`}>{c.url ? <a className="underline" href={c.url}>{c.text}</a> : c.text}</span>); }
function MediaImage({ media }: { media: Media }) { const url = resolveMediaUrl(media); if (!url) return null; return <div className="relative my-8 aspect-[16/9] overflow-hidden rounded-xl bg-slate-100"><ImageLightbox images={[{ src: url, alt: media.alternativeText ?? "" }]} className="h-full" /></div>; }
function normalizeMedia(value: unknown): Media | null { if (!value || typeof value !== "object") return null; const raw = value as Record<string, unknown>; const nested = raw.data && typeof raw.data === "object" ? raw.data as Record<string, unknown> : raw; const attributes = nested.attributes && typeof nested.attributes === "object" ? nested.attributes as Record<string, unknown> : nested; return typeof attributes.url === "string" ? attributes as Media : null; }
function blockImage(block: Block): Media | null { if (Array.isArray(block.image)) return normalizeMedia(block.image[0]); if (block.image) return normalizeMedia(block.image); if (typeof block.url === "string") return { url: block.url }; return null; }
export function RichTextRenderer({ blocks }: { blocks?: unknown[] | null }) { if (!blocks?.length) return null; return <div className="prose prose-slate max-w-none">{blocks.map((raw, i) => { const b = (raw ?? {}) as Block; const content = inline(b.children); if (b.__component === "shared.rich-text") return b.body ? <ReactMarkdown key={i} remarkPlugins={[remarkGfm]} components={{ h2: ({ children }) => <h2 className="mb-4 mt-10 text-3xl font-semibold tracking-tight text-slate-950">{children}</h2>, h3: ({ children }) => <h3 className="mb-3 mt-8 text-2xl font-semibold text-slate-950">{children}</h3>, p: ({ children }) => <p className="my-4 leading-8 text-slate-700">{children}</p>, ul: ({ children }) => <ul className="my-5 list-disc space-y-2 pl-6 text-slate-700">{children}</ul>, ol: ({ children }) => <ol className="my-5 list-decimal space-y-2 pl-6 text-slate-700">{children}</ol>, a: ({ children, href }) => <a href={resolveStrapiAssetUrl(href) ?? href} className="text-blue-700 underline">{children}</a>, img: ({ alt, src }) => { const imageUrl = typeof src === "string" ? resolveStrapiAssetUrl(src) : null; return imageUrl ? <span className="my-8 block aspect-[16/9] overflow-hidden rounded-xl bg-slate-100"><ImageLightbox images={[{ src: imageUrl, alt: alt ?? "" }]} className="h-full" /></span> : null; } }}>{b.body}</ReactMarkdown> : null; if (b.__component === "shared.quote") return <blockquote key={i}><p>{b.body}</p>{b.title ? <footer>{b.title}</footer> : null}</blockquote>; if (b.__component === "shared.media") return b.file ? <MediaImage key={i} media={b.file} /> : null; if (b.__component === "shared.slider") return <div key={i} className="my-8 grid gap-4 sm:grid-cols-2">{(b.files ?? []).map((media, mediaIndex) => <MediaImage key={`${media.url}-${mediaIndex}`} media={media} />)}</div>; if (b.type === "heading") { const Tag = (`h${Math.min(Math.max(b.level ?? 2, 2), 6)}`) as ElementType; return <Tag key={i}>{content}</Tag>; } if (b.type === "image") { const media = blockImage(b); return media ? <MediaImage key={i} media={media} /> : null; } if (b.type === "paragraph" || b.children) return <p key={i}>{content}</p>; return null; })}</div>; }
