import type { ElementType, ReactNode } from "react";
import Image from "next/image";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { Media } from "@/types/content";
import { resolveMediaUrl, resolveStrapiAssetUrl } from "@/lib/strapi/image";
type Block = { type?: string; __component?: string; body?: string | null; title?: string | null; file?: Media | null; files?: Media[] | null; children?: Array<{ text?: string; bold?: boolean; italic?: boolean; url?: string }>; level?: number; url?: string;[key: string]: unknown };
function inline(children: Block["children"]): ReactNode { return (children ?? []).map((c, i) => <span key={i} className={`${c.bold ? "font-semibold" : ""} ${c.italic ? "italic" : ""}`}>{c.url ? <a className="underline" href={c.url}>{c.text}</a> : c.text}</span>); }
function MediaImage({ media }: { media: Media }) { const url = resolveMediaUrl(media); if (!url) return null; return <div className="relative my-8 aspect-[16/9] overflow-hidden rounded-xl bg-slate-100"><Image src={url} alt={media.alternativeText ?? ""} fill sizes="(min-width: 768px) 768px, 100vw" className="object-cover" /></div>; }
export function RichTextRenderer({ blocks }: { blocks?: unknown[] | null }) { if (!blocks?.length) return null; return <div className="prose prose-slate max-w-none">{blocks.map((raw, i) => { const b = (raw ?? {}) as Block; const content = inline(b.children); if (b.__component === "shared.rich-text") return b.body ? <ReactMarkdown key={i} remarkPlugins={[remarkGfm]} components={{ h2: ({ children }) => <h2 className="mb-4 mt-10 text-3xl font-semibold tracking-tight text-slate-950">{children}</h2>, h3: ({ children }) => <h3 className="mb-3 mt-8 text-2xl font-semibold text-slate-950">{children}</h3>, p: ({ children }) => <p className="my-4 leading-8 text-slate-700">{children}</p>, ul: ({ children }) => <ul className="my-5 list-disc space-y-2 pl-6 text-slate-700">{children}</ul>, ol: ({ children }) => <ol className="my-5 list-decimal space-y-2 pl-6 text-slate-700">{children}</ol>, a: ({ children, href }) => <a href={resolveStrapiAssetUrl(href) ?? href} className="text-blue-700 underline">{children}</a>, img: ({ alt, src }) => { const imageUrl = typeof src === "string" ? resolveStrapiAssetUrl(src) : null; return imageUrl ? <img src={imageUrl} alt={alt ?? ""} /> : null; } }}>{b.body}</ReactMarkdown> : null; if (b.__component === "shared.quote") return <blockquote key={i}><p>{b.body}</p>{b.title ? <footer>{b.title}</footer> : null}</blockquote>; if (b.__component === "shared.media") return b.file ? <MediaImage key={i} media={b.file} /> : null; if (b.__component === "shared.slider") return <div key={i} className="my-8 grid gap-4 sm:grid-cols-2">{(b.files ?? []).map((media, mediaIndex) => <MediaImage key={`${media.url}-${mediaIndex}`} media={media} />)}</div>; if (b.type === "heading") { const Tag = (`h${Math.min(Math.max(b.level ?? 2, 2), 6)}`) as ElementType; return <Tag key={i}>{content}</Tag>; } if (b.type === "image" && typeof b.url === "string") { const imageUrl = resolveStrapiAssetUrl(b.url); return imageUrl ? <img key={i} src={imageUrl} alt="" /> : null; } if (b.type === "paragraph" || b.children) return <p key={i}>{content}</p>; return null; })}</div>; }
